name: Sonarqube file for static code analysis
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2     # Checkout the latest version of actions from Github
    - name: Set up JDK 11           # Use Java 11 version
      uses: actions/setup-java@v2   # Checkout the latest version of Java 11
      with:
        java-version: '11'
        distribution: 'temurin'     # Take Temurin version of JAVA (Similar to Alpine in Linux)
        cache: maven
    - name: Build with Maven Cloud
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=javaprojectreachabilityfirst -Dsonar.organization=javaprojectreachabilityfirst -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN #sonar:sonar is the goal which we need to execute this .yml file, projectKey & organization are derived from Sonarcloud i.e you need to create this manually on Sonarcloud and add organization and project here.
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
